services:
  evolution:
    image: atendai/evolution-api:v2.0.10
    container_name: evolution
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SERVER_URL=http://localhost:8081
      - AUTHENTICATION_API_KEY=minhaChaveSecreta123
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:postgres@evolution-postgres:5432/evolution
      - DATABASE_CONNECTION_CLIENT_NAME=evolution
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://evolution-redis:6379
      - LOG_LEVEL=INFO
      - QRCODE_LIMIT=10
      - CONFIG_SESSION_PHONE_CLIENT=SmileHub
      - CONFIG_SESSION_PHONE_NAME=Chrome
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - evolution
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: evolution-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=evolution
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution

  redis:
    image: redis:7-alpine
    container_name: evolution-redis
    restart: always
    networks:
      - evolution

volumes:
  evolution_instances:
  evolution_store:
  postgres_data:

networks:
  evolution:
    driver: bridge
